#!/usr/bin/env bash
# $Id$

# TODO
#  - no bounce if internal (hostname -d -> no bounce)

: ${TERM_PROG:=xterm}

usage()
{
	echo "usage: $0 [-v] [-B bounce-host] [-C commit-id] [-x termopt] prof [host ...]" >&2
	exit 1
}

die()
{
	echo "$0: $@" >&2
	exit 1
}

xscreen()
{
	local setcwd= xtargs=() cmd="\$SHELL" sshbounce=0
	local OPTARG OPTIND

	while getopts "Bc:d:x:" c; do
		case $c in
		B) sshbounce=1			;;
		c) cmd=$OPTARG			;;
		d) setcwd="cd '$OPTARG' &&"	;;
		x) xtargs+=("$OPTARG")		;;
		esac
	done
	shift $(($OPTIND - 1))

	local host=$1
	local name=$2

	local screen="screen -A -x -R"

	if [[ $TERM_PROG =~ xterm ]]; then
		xtargs+=(-xrm 'XTerm*allowTitleOps: false' -title "${host%%.*}: $name")
	fi

	local setverbose
	[ -n "$verbose" ] && setverbose='set -x && '

	if [ $sshbounce -eq 1 ]; then
		[ -n "$verbose" ] && set -x
		$TERM_PROG "${xtargs[@]}" -e ssh -t $bounce_host \
		    "$setverbose ssh -t $host '$setcwd $screen -S $name sh -${verbose}c \"$cmd\"'" &
		set +x
	else
		[ -n "$verbose" ] && set -x
		$TERM_PROG "${xtargs[@]}" -e ssh -t $host \
		    "$setverbose $setcwd $screen -S $name sh -${verbose}c '$cmd'" &
		set +x
	fi
}

set -e
. ../pfl/utils/daemon/pfl_daemon.sh
set +e

bounce_host=
commit=
xtopts=()
verbose=
while getopts "B:C:vx:" c; do
	case $c in
	B) bounce_host=$OPTARG		;;
	C) commit=$OPTARG		;;
	v) verbose=x			;;
	x) xtopts+=(-x "$OPTARG")	;;
	*) usage			;;
	esac
done
shift $(($OPTIND - 1))

[ $# -ge 1 ] || usage

prof=$1
shift

myhosts="$@"
set --

set -e
. ../inf/$prof/$prof.dcfg
set +e

[ $# -eq 0 ] && die $prof: unknown deployment

for ln; do
	host=${ln%%%*}
	t0=${ln#*%}
	_fl=${t0#*%}
	bounce=
	skip=0
	_srcdir=$srcdir

	while :; do
		fl="${_fl%%%*}"
		_fl="${_fl#*%}"

		case $fl in
		bounce)		bounce=-B		;;
		share)		skip=1; break		;;
		srcdir=*)	_srcdir=${fl#srcdir=}	;;
		esac

		# terminal condition for flags processing
		[ x"$fl" = x"$_fl" ] && break
	done

	[ $skip -eq 1 ] && continue

	if [ -n "$myhosts" ]; then
		skip=1
		for th in $myhosts; do
			if [[ $host =~ ^$th ]]; then
				skip=0
				break
			fi
		done
		[ $skip -eq 1 ] && continue
	fi

	xscreen "${xtopts[@]}" $bounce -d $_srcdir -c '			\
	    [ -n "$DISPLAY" ] || unset SSH_ASKPASS;			\
	    umask 2;							\
	    if [ -z "$MAKEFLAGS" ] && type nproc >/dev/null 2>&1; then	\
		    export MAKEFLAGS=-j$(nproc);			\
	    fi;								\
	    gmake up &&							\
	    gmake build >/dev/null &&					\
	    sudo gmake install; $SHELL' $host $prof.src
done
